---
image: docker:17.04-git
services:
- docker:17.04-dind
stages:
- build
- deploy

variables:
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

build admin:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $RELEASE_IMAGE .
    - docker tag $RELEASE_IMAGE "$CI_REGISTRY_IMAGE:latest"
    - docker push $RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - /master|develop/
  tags:
    - docker


deploy to production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment Production --stack polis-dev --service polis-admin --new-image $RELEASE_IMAGE --no-finish-upgrade
  only:
    - /master|develop/
  environment: production
  tags:
    - docker
